config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get 'home' => 'static_pages#home'

  get 'signup' => 'users#new'
  resources :users
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :categories
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
  
  validates :name, presence: true, length: {minimum: 2, maximum: 75}
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  
  validates :user_id, :category_id, presence: true
  validates :title, presence: true, length: {minimum: 5, maximum: 75}
  validates :description, presence: true, length: {minimum: 25, maximum: 10000}
  validates :company, presence: true, length: {minimum: 3, maximum: 75}
  validates :location, presence: true, length: {minimum: 3, maximum: 75}
  validates_inclusion_of :active, :in => [true, false]
  
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: EMAIL_REGEX }
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :default_values, on: :create
  
  has_many :jobs
  
  ROLES = %w[user admin]
  
  has_secure_password
  
  validates :first_name, presence: true, length: {minimum: 3, maximum: 40}
  validates :last_name, presence: true, length: {minimum: 3, maximum: 75}
                   
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
  validates :password, presence: true, length: { minimum: 6, maximum: 40}, allow_nil: true
    
  def default_values
    if self.role.nil?
       self.role = "user" 
    end    
  end
  
  def admin?
    self.role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :admin_role?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
    flash[:success] = "Logout Successful!"
    redirect_to root_path
  end
  
  def admin_role?
    unless @current_user.admin?
      redirect_to current_user
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authorize
  before_action :admin_role?
  
  def index
  end

  def show
  end

  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    
    if @category.save
        flash[:success] = "Category successfully created!"
        redirect_to @category
    else
      render 'new'
    end
  end

  def edit
  end
  
  private
  
  def category_params
      params.require(:category).permit(:name)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  
  def index
  end
  
  def show
  end
  
  def new
  end
  
  def create
  end

  def edit
  end
  
  def update
  end
  
  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    
    if user && user.authenticate(params[:password])  
      session[:user_id] = user.id
      flash[:success] = 'Login Successful!'
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination'
      redirect_to login_path
    end
  end
  
  def destroy
    log_out
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create]
  before_action :check_user, except: [:new, :create, :index]
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
        session[:user_id] = @user.id
        flash[:success] = "Signup Successful!"
        redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      
      flash[:success] = "Profile successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User successfully destroyed."
    log_out
  end
  
  private
  
  def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role)
  end
  
  def check_user
    @user = User.find(params[:id])
    
    unless @user == current_user
      redirect_to current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.haml
.row
  = form_for(@category) do |f|

    = render 'shared/error_communicat', object: f.object

    .form-inputs
      .field
        = f.label :name
        = f.text_field :name
    
    .form-action
      = f.submit locals[:button], class: "btn btn-success"

app/views/categories/edit.html.haml
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.haml
= link_to "New category", new_category_path

app/views/categories/new.html.haml
.center
  %h1 New category   
  = render 'form', locals: {button: "Create category"}

app/views/categories/show.html.haml
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/jobs/edit.html.haml
<h1>Jobs#edit</h1>
<p>Find me in app/views/jobs/edit.html.erb</p>

app/views/jobs/new.html.haml
<h1>Jobs#new</h1>
<p>Find me in app/views/jobs/new.html.erb</p>

app/views/jobs/show.html.haml
<h1>Jobs#show</h1>
<p>Find me in app/views/jobs/show.html.erb</p>

app/views/layouts/_flash_communicat.html.haml
- flash.each do |message_type, message|
  .alert{ class: "alert-#{message_type}" }= message

app/views/layouts/_footer.html.haml
%footer &copy; MaT

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-default
    .navbar-fluid
      .navbar-header
        = link_to "Easy-Hire", root_path, class: 'navbar-brand'
      .navbar-collapse.collapse#navbar
        %ul.nav.navbar-nav
          %li
            = link_to "Home", root_path
        %ul.nav.navbar-nav.navbar-right
          - if current_user
            - if current_user.admin?
              %li
                = link_to "Categories", categories_path
            %li
              = link_to "Edit profile", edit_user_path(current_user)  
            %li
              = link_to "Log out", logout_path, method: "delete"
          - else
            %li
              = link_to "Sign up", signup_path
            %li
              = link_to "Log in", login_path, method: "get"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Easy-Hire
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
     
    = render 'layouts/header'
    .content
      = render 'layouts/flash_communicat'
      = yield
    = render 'layouts/footer'

app/views/shared/_error_communicat.html.haml
- if object.errors.any?
  .error_explanation
    .alert.alert-danger
      %ul
        - object.errors.full_messages.each do |msg|
          %li= msg

app/views/static_pages/home.html.haml
.center
  .home
    %p.title Easy-Hire
    %p Are you looking for a worker? If so this website is just for you!
    = link_to "Sign up!", signup_path, class: 'btn btn-lg btn-success'

app/views/users/_form.html.haml
.row
  = form_for(@user) do |f|

    = render 'shared/error_communicat', object: f.object

    .form-inputs
      .field
        = f.label :first_name
        = f.text_field :first_name
    
      .field
        = f.label :last_name
        = f.text_field :last_name
    
      .field
        = f.label :email
        = f.email_field :email
      
      .field
        = f.label :password
        = f.password_field :password
      
      .field
        = f.label :password_confirmation, "Password confirmation"
        = f.password_field :password_confirmation
    
    .form-action
      = f.submit locals[:button], class: "btn btn-success"

app/views/users/edit.html.haml
.user-form
  %h1 Edit profile      
  = render 'form', locals: {button: "Save changes"}
  
  .line
    %hr
  .delete-user
    = link_to "Delete your account", @user, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"

app/views/users/new.html.haml
.user-form
  %h1 Sign up      
  = render 'form', locals: {button: "Create My Account"}

app/views/users/show.html.haml
Welcome
%br
= @user.id